### ISSUE TITLE
Build Issues UE 4.25 on Linux

### ISSUE THREAD

**Issue by godofdream** [KoderzUnreal/RuntimeMeshComponent#167]
I've added the Repository to the Plugins Folder in my Project.
During opening UE4Editor wants to rebuild RuntimeMeshComponent and fails.
UE 4.25 on Ubuntu 20.04 with clang 9.01
My Project opens/builds without this plugin.

```
./Engine/Binaries/Linux/UE4Editor /home/msowka/Dokumente/Unreal\ Projects/Procedural-Cities/City.uproject 
Increasing per-process limit of core file size to infinity.
LogInit: Display: Running engine for game: City
LogPlatformFile: Not using cached read wrapper
LogTaskGraph: Started task graph with 5 named threads and 20 total threads with 3 sets of task threads.
LogStats: Stats thread started at 0.091591
LogICUInternationalization: ICU TimeZone Detection - Raw Offset: +1:00, Platform Override: ''
LogPluginManager: Mounting plugin Niagara
LogPluginManager: Mounting plugin VariantManagerContent
LogPluginManager: Mounting plugin DatasmithContent
LogPluginManager: Mounting plugin MeshPainting
LogPluginManager: Mounting plugin AISupport
LogPluginManager: Mounting plugin Paper2D
LogPluginManager: Mounting plugin MovieRenderPipeline
LogPluginManager: Mounting plugin TemplateSequence
LogPluginManager: Mounting plugin ActorSequence
LogPluginManager: Mounting plugin LevelSequenceEditor
LogPluginManager: Mounting plugin MatineeToLevelSequence
LogPluginManager: Mounting plugin OnlineSubsystemIOS
LogPluginManager: Mounting plugin OnlineSubsystemUtils
LogPluginManager: Mounting plugin OnlineSubsystemGooglePlay
LogPluginManager: Mounting plugin OnlineSubsystemNull
LogPluginManager: Mounting plugin OnlineSubsystem
LogPluginManager: Mounting plugin NetcodeUnitTest
LogPluginManager: Mounting plugin NUTUnrealEngine4
LogPluginManager: Mounting plugin LightPropagationVolume
LogPluginManager: Mounting plugin AvfMedia
LogPluginManager: Mounting plugin AndroidMedia
LogPluginManager: Mounting plugin WebMMedia
LogPluginManager: Mounting plugin ImgMedia
LogPluginManager: Mounting plugin MediaCompositing
LogPluginManager: Mounting plugin MediaPlayerEditor
LogPluginManager: Mounting plugin WmfMedia
LogPluginManager: Mounting plugin MagicLeap
LogPluginManager: Mounting plugin MagicLeapLightEstimation
LogPluginManager: Mounting plugin MagicLeapPassableWorld
LogPluginManager: Mounting plugin MLSDK
LogPluginManager: Mounting plugin MagicLeapMedia
LogPluginManager: Mounting plugin GeometryMode
LogPluginManager: Mounting plugin MaterialAnalyzer
LogPluginManager: Mounting plugin CurveEditorTools
LogPluginManager: Mounting plugin CryptoKeys
LogPluginManager: Mounting plugin GameplayTagsEditor
LogPluginManager: Mounting plugin DataValidation
LogPluginManager: Mounting plugin MobileLauncherProfileWizard
LogPluginManager: Mounting plugin MacGraphicsSwitching
LogPluginManager: Mounting plugin PluginBrowser
LogPluginManager: Mounting plugin EditorScriptingUtilities
LogPluginManager: Mounting plugin FacialAnimation
LogPluginManager: Mounting plugin SpeedTreeImporter
LogPluginManager: Mounting plugin AssetManagerEditor
LogPluginManager: Mounting plugin UdpMessaging
LogPluginManager: Mounting plugin TcpMessaging
LogPluginManager: Mounting plugin CameraShakePreviewer
LogPluginManager: Mounting plugin AutomationUtils
LogPluginManager: Mounting plugin ChaosClothEditor
LogPluginManager: Mounting plugin ChaosSolverPlugin
LogPluginManager: Mounting plugin ProxyLODPlugin
LogPluginManager: Mounting plugin PlanarCut
LogPluginManager: Mounting plugin GeometryProcessing
LogPluginManager: Mounting plugin SkeletalReduction
LogPluginManager: Mounting plugin AlembicImporter
LogPluginManager: Mounting plugin ChaosNiagara
LogPluginManager: Mounting plugin ChaosEditor
LogPluginManager: Mounting plugin BackChannel
LogPluginManager: Mounting plugin CharacterAI
LogPluginManager: Mounting plugin GeometryCache
LogPluginManager: Mounting plugin ChaosCloth
LogPluginManager: Mounting plugin PlatformCrypto
LogPluginManager: Mounting plugin GeometryCollectionPlugin
LogPluginManager: Mounting plugin ScreenshotTools
LogPluginManager: Mounting plugin AnimationSharing
LogPluginManager: Mounting plugin SubversionSourceControl
LogPluginManager: Mounting plugin XCodeSourceCodeAccess
LogPluginManager: Mounting plugin PerforceSourceControl
LogPluginManager: Mounting plugin KDevelopSourceCodeAccess
LogPluginManager: Mounting plugin NullSourceCodeAccess
LogPluginManager: Mounting plugin GitSourceControl
LogPluginManager: Mounting plugin UObjectPlugin
LogPluginManager: Mounting plugin PlasticSourceControl
LogPluginManager: Mounting plugin CodeLiteSourceCodeAccess
LogPluginManager: Mounting plugin VisualStudioSourceCodeAccess
LogPluginManager: Mounting plugin CLionSourceCodeAccess
LogPluginManager: Mounting plugin RiderSourceCodeAccess
LogPluginManager: Mounting plugin VisualStudioCodeSourceCodeAccess
LogPluginManager: Mounting plugin ActorLayerUtilities
LogPluginManager: Mounting plugin CableComponent
LogPluginManager: Mounting plugin ArchVisCharacter
LogPluginManager: Mounting plugin AppleImageUtils
LogPluginManager: Mounting plugin AndroidPermission
LogPluginManager: Mounting plugin PostSplashScreen
LogPluginManager: Mounting plugin AppleMoviePlayer
LogPluginManager: Mounting plugin AndroidMoviePlayer
LogPluginManager: Mounting plugin SoundFields
LogPluginManager: Mounting plugin LinuxDeviceProfileSelector
LogPluginManager: Mounting plugin ProceduralMeshComponent
LogPluginManager: Mounting plugin AndroidDeviceProfileSelector
LogPluginManager: Mounting plugin IOSDeviceProfileSelector
LogPluginManager: Mounting plugin MobilePatchingUtils
LogPluginManager: Mounting plugin GoogleCloudMessaging
LogPluginManager: Mounting plugin SteamVR
LogPluginManager: Mounting plugin SignificanceManager
LogPluginManager: Mounting plugin ExampleDeviceProfileSelector
LogPluginManager: Mounting plugin LocationServicesBPLibrary
LogPluginManager: Mounting plugin RuntimePhysXCooking
LogPluginManager: Mounting plugin GooglePAD
LogPluginManager: Mounting plugin WindowsMoviePlayer
LogPluginManager: Mounting plugin PhysXVehicles
LogPluginManager: Mounting plugin WebMMoviePlayer
LogPluginManager: Mounting plugin AudioCapture
LogPluginManager: Mounting plugin Synthesis
LogPluginManager: Mounting plugin AssetTags
LogPluginManager: Mounting plugin EditableMesh
LogPluginManager: Mounting plugin CustomMeshComponent
LogPluginManager: Mounting plugin OculusVR
LogPluginManager: Mounting plugin LauncherChunkInstaller
LogPluginManager: Mounting plugin RuntimeMeshComponent
LogInit: Warning: Incompatible or missing module: RuntimeMeshComponent
LogInit: Warning: Incompatible or missing module: RuntimeMeshComponentEditor
LogInit: Initializing SDL.
LogInit: Initialized SDL 2.0.10 revision: 12952 (hg-12952:bc90ce38f1e2) (compiled against 2.0.10)
LogInit: Using SDL video driver 'x11'
LogInit: Display metrics:
LogInit:   PrimaryDisplayWidth: 3840
LogInit:   PrimaryDisplayHeight: 2160
LogInit:   PrimaryDisplayWorkAreaRect:
LogInit:     Left=3840, Top=1080, Right=7680, Bottom=3200
LogInit:   VirtualDisplayRect:
LogInit:     Left=0, Top=0, Right=7680, Bottom=3240
LogInit:   TitleSafePaddingSize: X=0.000 Y=0.000 Z=0.000 W=0.000
LogInit:   ActionSafePaddingSize: X=0.000 Y=0.000 Z=0.000 W=0.000
LogInit:   Number of monitors: 4
LogInit:     Monitor 0
LogInit:       Name: SWEDX TV 32"
LogInit:       ID: display0
LogInit:       NativeWidth: 3840
LogInit:       NativeHeight: 2160
LogInit:       bIsPrimary: true
LogInit:     Monitor 1
LogInit:       Name: BenQ G2420HD 24"
LogInit:       ID: display1
LogInit:       NativeWidth: 1920
LogInit:       NativeHeight: 1080
LogInit:       bIsPrimary: false
LogInit:     Monitor 2
LogInit:       Name: SWEDX TV 32"
LogInit:       ID: display2
LogInit:       NativeWidth: 3840
LogInit:       NativeHeight: 2160
LogInit:       bIsPrimary: false
LogInit:     Monitor 3
LogInit:       Name: SyncMaster 24"
LogInit:       ID: display3
LogInit:       NativeWidth: 1920
LogInit:       NativeHeight: 1080
LogInit:       bIsPrimary: false
STUBBED: FDesktopPlatformLinux::GetNativeFeedbackContext at /media/msowka/4TB/Unreal Engine/4.45/UnrealEngine/Engine/Source/Developer/DesktopPlatform/Private/Linux/DesktopPlatformLinux.cpp:450 (GetNativeFeedbackContext)
Running /media/msowka/4TB/Unreal Engine/4.45/UnrealEngine/Engine/Binaries/DotNET/UnrealBuildTool.exe Development Linux -Project="/home/msowka/Dokumente/Unreal Projects/Procedural-Cities/City.uproject" -TargetType=Editor -Progress -NoEngineChanges -NoHotReloadFromIDE

Running Mono...

Fixing inconsistent case in filenames.
Setting up Mono
/media/msowka/4TB/Unreal Engine/4.45/UnrealEngine/Engine /media/msowka/4TB/Unreal Engine/4.45/UnrealEngine/Engine/Binaries/Linux
Using 'git status' to determine working set for adaptive non-unity build (/media/msowka/4TB/Unreal Engine/4.45/UnrealEngine).
Using 'git status' to determine working set for adaptive non-unity build (/home/msowka/Dokumente/Unreal Projects/Procedural-Cities).
Invalidating makefile for CityEditor (RuntimeMeshComponent.uplugin has been added)
@progress push 5%
@progress push 5%
@progress pop
Parsing headers for CityEditor
  Running UnrealHeaderTool "/home/msowka/Dokumente/Unreal Projects/Procedural-Cities/City.uproject" "/home/msowka/Dokumente/Unreal Projects/Procedural-Cities/Intermediate/Build/Linux/B4D820EA/CityEditor/Development/CityEditor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -abslog="/media/msowka/4TB/Unreal Engine/4.45/UnrealEngine/Engine/Programs/UnrealBuildTool/Log_UHT.txt"
Reflection code generated for CityEditor in 4,9449288 seconds
@progress pop
------- Build details --------
Using toolchain located at '/media/msowka/4TB/Unreal Engine/4.45/UnrealEngine/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v16_clang-9.0.1-centos7/x86_64-unknown-linux-gnu'.
Using clang (/media/msowka/4TB/Unreal Engine/4.45/UnrealEngine/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v16_clang-9.0.1-centos7/x86_64-unknown-linux-gnu/bin/clang++) version '9.0.1' (string), 9 (major), 0 (minor), 1 (patch)
Using bundled libc++ standard C++ library.
Using lld linker
Using llvm-ar : /media/msowka/4TB/Unreal Engine/4.45/UnrealEngine/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v16_clang-9.0.1-centos7/x86_64-unknown-linux-gnu/bin/llvm-ar
Using fast way to relink  circularly dependent libraries (no FixDeps).
------------------------------
ERROR: Building would modify the following engine files:
       
       /media/msowka/4TB/Unreal Engine/4.45/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/Engine/SharedPCH.Engine.h.d
       /media/msowka/4TB/Unreal Engine/4.45/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/Engine/SharedPCH.Engine.h.gch
       /media/msowka/4TB/Unreal Engine/4.45/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/UnrealEd/SharedPCH.UnrealEd.h.d
       /media/msowka/4TB/Unreal Engine/4.45/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/UnrealEd/SharedPCH.UnrealEd.h.gch
       
       Please rebuild from an IDE instead.
LogCore: Engine exit requested (reason: EngineExit() was called)
LogExit: Preparing to exit.
LogModuleManager: Shutting down and abandoning module DesktopPlatform (44)
LogModuleManager: Shutting down and abandoning module PlatformCryptoOpenSSL (42)
LogModuleManager: Shutting down and abandoning module PlatformCryptoTypes (40)
LogModuleManager: Shutting down and abandoning module PlatformCrypto (38)
LogModuleManager: Shutting down and abandoning module AnimationModifiers (36)
LogModuleManager: Shutting down and abandoning module PropertyEditor (35)
LogModuleManager: Shutting down and abandoning module AudioEditor (32)
LogModuleManager: Shutting down and abandoning module TextureCompressor (30)
LogModuleManager: Shutting down and abandoning module RenderCore (28)
LogModuleManager: Shutting down and abandoning module Landscape (26)
LogModuleManager: Shutting down and abandoning module SlateRHIRenderer (24)
LogModuleManager: Shutting down and abandoning module OpenGLDrv (22)
LogModuleManager: Shutting down and abandoning module AnimGraphRuntime (20)
LogModuleManager: Shutting down and abandoning module Renderer (18)
LogModuleManager: Shutting down and abandoning module Engine (16)
LogModuleManager: Shutting down and abandoning module CoreUObject (14)
LogModuleManager: Shutting down and abandoning module NetworkFile (12)
LogModuleManager: Shutting down and abandoning module CookedIterativeFile (10)
LogModuleManager: Shutting down and abandoning module StreamingFile (8)
LogModuleManager: Shutting down and abandoning module SandboxFile (6)
LogModuleManager: Shutting down and abandoning module PakFile (4)
LogModuleManager: Shutting down and abandoning module RSA (3)
LogExit: Exiting.
LogInit: Tearing down SDL.
Exiting abnormally (error code: 1)
```
Any Idea

**Comment by Koderz** [comment]
Appears you need to rebuild from an IDE. The log there doesn't really explain why it failed.

"ERROR: Building would modify the following engine files:"  makes no real sense, but it's directly asking to rebuild from an IDE instead so I'd try that.

**Comment by Koderz** [comment]
To my knowledge the RMC will build on Linux at this point so I'm closing this one. If there's any further issues with this or anything else feel free to reopen this or submit a new bug!

Thanks!

**Comment by dennismozart1994** [comment]
That's still a thing on 4.25.1

We cannot build either from IDE or directly through the UnrealEngine itself.

In 4.24 this didn't use to happen though.
UnrealEngine/Engine/Source/Developer/DesktopPlatform/Private/Linux/DesktopPlatformLinux.cpp:450

**Comment by dennismozart1994** [comment]
@Koderz here's the log of the QT Creator ehwn trying to build from IDE for example:

`18:17:44: Starting /home/dennis/UnrealEngine/Engine/Binaries/Linux/UE4Editor "/home/dennis/Study/Study.uproject"...
Increasing per-process limit of core file size to infinity.
LogInit: Display: Running engine for game: Study
LogPlatformFile: Not using cached read wrapper
LogTaskGraph: Started task graph with 5 named threads and 26 total threads with 3 sets of task threads.
LogStats: Stats thread started at 0.119183
LogICUInternationalization: ICU TimeZone Detection - Raw Offset: -3:00, Platform Override: ''
LogPluginManager: Mounting plugin BackChannel
LogPluginManager: Mounting plugin RawInput
LogPluginManager: Mounting plugin SkeletalReduction
LogPluginManager: Mounting plugin ChaosNiagara
LogPluginManager: Mounting plugin GeometryCollectionPlugin
LogPluginManager: Mounting plugin AutomationUtils
LogPluginManager: Mounting plugin ChaosCloth
LogPluginManager: Mounting plugin ChaosEditor
LogPluginManager: Mounting plugin PlanarCut
LogPluginManager: Mounting plugin ChaosSolverPlugin
LogPluginManager: Mounting plugin ProxyLODPlugin
LogPluginManager: Mounting plugin GeometryProcessing
LogPluginManager: Mounting plugin PlatformCrypto
LogPluginManager: Mounting plugin ChaosClothEditor
LogPluginManager: Mounting plugin CharacterAI
LogPluginManager: Mounting plugin AlembicImporter
LogPluginManager: Mounting plugin GeometryCache
LogPluginManager: Mounting plugin UdpMessaging
LogPluginManager: Mounting plugin TcpMessaging
LogPluginManager: Mounting plugin CodeLiteSourceCodeAccess
LogPluginManager: Mounting plugin CLionSourceCodeAccess
LogPluginManager: Mounting plugin AnimationSharing
LogPluginManager: Mounting plugin RiderSourceCodeAccess
LogPluginManager: Mounting plugin SubversionSourceControl
LogPluginManager: Mounting plugin KDevelopSourceCodeAccess
LogPluginManager: Mounting plugin PlasticSourceControl
LogPluginManager: Mounting plugin PerforceSourceControl
LogPluginManager: Mounting plugin XCodeSourceCodeAccess
LogPluginManager: Mounting plugin UObjectPlugin
LogPluginManager: Mounting plugin VisualStudioSourceCodeAccess
LogPluginManager: Mounting plugin VisualStudioCodeSourceCodeAccess
LogPluginManager: Mounting plugin GitSourceControl
LogPluginManager: Mounting plugin ActorLayerUtilities
LogPluginManager: Mounting plugin NullSourceCodeAccess
LogPluginManager: Mounting plugin NetcodeUnitTest
LogPluginManager: Mounting plugin NUTUnrealEngine4
LogPluginManager: Mounting plugin OnlineSubsystemGooglePlay
LogPluginManager: Mounting plugin OnlineSubsystemUtils
LogPluginManager: Mounting plugin OnlineSubsystem
LogPluginManager: Mounting plugin OnlineSubsystemNull
LogPluginManager: Mounting plugin OnlineSubsystemIOS
LogPluginManager: Mounting plugin Paper2D
LogPluginManager: Mounting plugin MeshPainting
LogPluginManager: Mounting plugin Niagara
LogPluginManager: Mounting plugin SoundFields
LogPluginManager: Mounting plugin MobilePatchingUtils
LogPluginManager: Mounting plugin ArchVisCharacter
LogPluginManager: Mounting plugin SignificanceManager
LogPluginManager: Mounting plugin GoogleCloudMessaging
LogPluginManager: Mounting plugin LocationServicesBPLibrary
LogPluginManager: Mounting plugin OculusVR
LogPluginManager: Mounting plugin AppleMoviePlayer
LogPluginManager: Mounting plugin PostSplashScreen
LogPluginManager: Mounting plugin ProceduralMeshComponent
LogPluginManager: Mounting plugin AudioCapture
LogPluginManager: Mounting plugin AssetTags
LogPluginManager: Mounting plugin WebMMoviePlayer
LogPluginManager: Mounting plugin SteamVR
LogPluginManager: Mounting plugin AndroidPermission
LogPluginManager: Mounting plugin PhysXVehicles
LogPluginManager: Mounting plugin AndroidDeviceProfileSelector
LogPluginManager: Mounting plugin WindowsMoviePlayer
LogPluginManager: Mounting plugin EditableMesh
LogPluginManager: Mounting plugin RuntimePhysXCooking
LogPluginManager: Mounting plugin AppleImageUtils
LogPluginManager: Mounting plugin ExampleDeviceProfileSelector
LogPluginManager: Mounting plugin GooglePAD
LogPluginManager: Mounting plugin CableComponent
LogPluginManager: Mounting plugin IOSDeviceProfileSelector
LogPluginManager: Mounting plugin Synthesis
LogPluginManager: Mounting plugin LinuxDeviceProfileSelector
LogPluginManager: Mounting plugin STUBBED: FDesktopPlatformLinux::GetNativeFeedbackContext at /home/dennis/UnrealEngine/Engine/Source/Developer/DesktopPlatform/Private/Linux/DesktopPlatformLinux.cpp:450 (GetNativeFeedbackContext)
AndroidMoviePlayer
LogPluginManager: Mounting plugin CustomMeshComponent
LogPluginManager: Mounting plugin AISupport
LogPluginManager: Mounting plugin MatineeToLevelSequence
LogPluginManager: Mounting plugin TemplateSequence
LogPluginManager: Mounting plugin LevelSequenceEditor
LogPluginManager: Mounting plugin ActorSequence
LogPluginManager: Mounting plugin MovieRenderPipeline
LogPluginManager: Mounting plugin CameraShakePreviewer
LogPluginManager: Mounting plugin MLSDK
LogPluginManager: Mounting plugin MagicLeapLightEstimation
LogPluginManager: Mounting plugin MagicLeapMedia
LogPluginManager: Mounting plugin MagicLeap
LogPluginManager: Mounting plugin MagicLeapPassableWorld
LogPluginManager: Mounting plugin GameplayTagsEditor
LogPluginManager: Mounting plugin CurveEditorTools
LogPluginManager: Mounting plugin SpeedTreeImporter
LogPluginManager: Mounting plugin MacGraphicsSwitching
LogPluginManager: Mounting plugin EditorScriptingUtilities
LogPluginManager: Mounting plugin PluginBrowser
LogPluginManager: Mounting plugin MobileLauncherProfileWizard
LogPluginManager: Mounting plugin MaterialAnalyzer
LogPluginManager: Mounting plugin CryptoKeys
LogPluginManager: Mounting plugin GeometryMode
LogPluginManager: Mounting plugin FacialAnimation
LogPluginManager: Mounting plugin AssetManagerEditor
LogPluginManager: Mounting plugin DataValidation
LogPluginManager: Mounting plugin VariantManagerContent
LogPluginManager: Mounting plugin DatasmithContent
LogPluginManager: Mounting plugin LightPropagationVolume
LogPluginManager: Mounting plugin LauncherChunkInstaller
LogPluginManager: Mounting plugin ScreenshotTools
LogPluginManager: Mounting plugin WmfMedia
LogPluginManager: Mounting plugin WebMMedia
LogPluginManager: Mounting plugin AvfMedia
LogPluginManager: Mounting plugin MediaCompositing
LogPluginManager: Mounting plugin ImgMedia
LogPluginManager: Mounting plugin AndroidMedia
LogPluginManager: Mounting plugin MediaPlayerEditor
LogInit: Warning: Incompatible or missing module: Study
LogInit: Initializing SDL.
LogInit: Initialized SDL 2.0.10 revision: 12952 (hg-12952:bc90ce38f1e2) (compiled against 2.0.10)
LogInit: Using SDL video driver 'x11'
LogInit: Display metrics:
LogInit:   PrimaryDisplayWidth: 1360
LogInit:   PrimaryDisplayHeight: 768
LogInit:   PrimaryDisplayWorkAreaRect:
LogInit:     Left=72, Top=27, Right=1360, Bottom=768
LogInit:   VirtualDisplayRect:
LogInit:     Left=72, Top=27, Right=1360, Bottom=768
LogInit:   TitleSafePaddingSize: X=0.000 Y=0.000 Z=0.000 W=0.000
LogInit:   ActionSafePaddingSize: X=0.000 Y=0.000 Z=0.000 W=0.000
LogInit:   Number of monitors: 1
LogInit:     Monitor 0
LogInit:       Name: AOC LCD 24"
LogInit:       ID: display0
LogInit:       NativeWidth: 1360
LogInit:       NativeHeight: 768
LogInit:       bIsPrimary: true
Running /home/dennis/UnrealEngine/Engine/Binaries/DotNET/UnrealBuildTool.exe Development Linux -Project="/home/dennis/Study/Study.uproject" -TargetType=Editor -Progress -NoEngineChanges -NoHotReloadFromIDE

Running Mono...

Fixing inconsistent case in filenames.
Setting up Mono
~/UnrealEngine/Engine ~/UnrealEngine/Engine/Binaries/Linux
WARNING: Trying to build an enterprise target but the enterprise directory is missing. Falling back on engine components only.
Using 'git status' to determine working set for adaptive non-unity build (/home/dennis/UnrealEngine).
Using 'git status' to determine working set for adaptive non-unity build (/home/dennis/Study).
Creating makefile for StudyEditor (no existing makefile)
@progress push 5%
@progress push 5%
@progress pop
Parsing headers for StudyEditor
  Running UnrealHeaderTool "/home/dennis/Study/Study.uproject" "/home/dennis/Study/Intermediate/Build/Linux/B4D820EA/StudyEditor/Development/StudyEditor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -abslog="/home/dennis/UnrealEngine/Engine/Programs/UnrealBuildTool/Log_UHT.txt"
Reflection code generated for StudyEditor in 6.4354034 seconds
@progress pop
------- Build details --------
Using toolchain located at '/home/dennis/UnrealEngine/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v16_clang-9.0.1-centos7/x86_64-unknown-linux-gnu'.
Using clang (/home/dennis/UnrealEngine/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v16_clang-9.0.1-centos7/x86_64-unknown-linux-gnu/bin/clang++) version '9.0.1' (string), 9 (major), 0 (minor), 1 (patch)
Using bundled libc++ standard C++ library.
Using lld linker
Using llvm-ar : /home/dennis/UnrealEngine/Engine/Extras/ThirdPartyNotUE/SDKs/HostLinux/Linux_x64/v16_clang-9.0.1-centos7/x86_64-unknown-linux-gnu/bin/llvm-ar
Using fast way to relink  circularly dependent libraries (no FixDeps).
------------------------------
ERROR: Building would modify the following engine files:
       
       /home/dennis/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/Engine/SharedPCH.Engine.h.d
       /home/dennis/UnrealEngine/Engine/Intermediate/Build/Linux/B4D820EA/UE4Editor/Development/Engine/SharedPCH.Engine.h.gch
       
       Please rebuild from an IDE instead.
LogCore: Engine exit requested (reason: EngineExit() was called)
LogExit: Preparing to exit.
LogModuleManager: Shutting down and abandoning module DesktopPlatform (44)
LogModuleManager: Shutting down and abandoning module PlatformCryptoOpenSSL (42)
LogModuleManager: Shutting down and abandoning module PlatformCryptoTypes (40)
LogModuleManager: Shutting down and abandoning module PlatformCrypto (38)
LogModuleManager: Shutting down and abandoning module AnimationModifiers (36)
LogModuleManager: Shutting down and abandoning module PropertyEditor (35)
LogModuleManager: Shutting down and abandoning module AudioEditor (32)
LogModuleManager: Shutting down and abandoning module TextureCompressor (30)
LogModuleManager: Shutting down and abandoning module RenderCore (28)
LogModuleManager: Shutting down and abandoning module Landscape (26)
LogModuleManager: Shutting down and abandoning module SlateRHIRenderer (24)
LogModuleManager: Shutting down and abandoning module OpenGLDrv (22)
LogModuleManager: Shutting down and abandoning module AnimGraphRuntime (20)
LogModuleManager: Shutting down and abandoning module Renderer (18)
LogModuleManager: Shutting down and abandoning module Engine (16)
LogModuleManager: Shutting down and abandoning module CoreUObject (14)
LogModuleManager: Shutting down and abandoning module NetworkFile (12)
LogModuleManager: Shutting down and abandoning module CookedIterativeFile (10)
LogModuleManager: Shutting down and abandoning module StreamingFile (8)
LogModuleManager: Shutting down and abandoning module SandboxFile (6)
LogModuleManager: Shutting down and abandoning module PakFile (4)
LogModuleManager: Shutting down and abandoning module RSA (3)
LogExit: Exiting.
LogInit: Tearing down SDL.
Exiting abnormally (error code: 1)
18:18:43: /home/dennis/UnrealEngine/Engine/Binaries/Linux/UE4Editor exited with code 1`
