### ISSUE TITLE
Update needed for 4.25 compiling.

### ISSUE THREAD

**Issue by alatnet** [KoderzUnreal/RuntimeMeshComponent#168]
Got a really simple error while compiling in VSC.
Says to update bOpaqueRelevance to bOpaque on line 116 in RuntimeMeshComponentProxy.cpp.
Will compile fine afterwards.

**Comment by alatnet** [comment]
Ah, looks like categories need to be placed on various things for blueprints...

**Comment by SliceOfCheese-978** [comment]
I'm getting the exact same error, and I don't know how to fix it :(

**Comment by Koderz** [comment]
I believe these have been fixed in the current version! Thanks for the report! If you have any further issues with this or anything else feel free to let me know!
