### ISSUE TITLE
RuntimeMesh from static mesh causes: - Assertion failed: Pair != nullptr 

### ISSUE THREAD

**Issue by samuraironi** [KoderzUnreal/RuntimeMeshComponent#172]
Hello,
I'm trying to create a runtime mesh from static mesh using URuntimeMeshProviderStaticMesh,
but when I add a static mesh I get the Assertion Failed error in the `RuntimeMeshStaticMeshConvert.cpp` at line 149, I didn't find any solution for this. I've tried to create a runtime mesh from staticmesh that was created from SM_Sedan skeletal mesh (from samples).
But maybe I'm using wrong provider for this task. 
Thanks for help!

**Comment by JackMaDrinkCoffee** [comment]
I am so sorry that I have already giving up the RuntimeMesh plugin by using proceduralMeshComponent! So the questions you ask I dont know how to resolve ! sorry about that!












------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"samuraironi"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月21日(星期四) 凌晨3:06
收件人:&nbsp;"Koderz/RuntimeMeshComponent"<RuntimeMeshComponent@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Koderz/RuntimeMeshComponent] RuntimeMesh from static mesh causes: - Assertion failed: Pair != nullptr  (#172)





 
Hello,
 I'm trying to create a runtime mesh from static mesh using URuntimeMeshProviderStaticMesh,
 but when I add a static mesh I get the Assertion Failed error in the RuntimeMeshStaticMeshConvert.cpp at line 149, I didn't find any solution for this. I've tried to create a runtime mesh from staticmesh that was created from SM_Sedan skeletal mesh (from samples).
 But maybe I'm using wrong provider for this task.
 Thanks for help!

**Comment by Koderz** [comment]
Is this still an issue with the current version?

**Comment by samuraironi** [comment]
I will try today evening. But looks like I found the problem. It's somwhere in my Materials. So I had lot of material slots (8 or 10), I tried to remove all the materials and just import an object without them. And everythig looks fine.
