### ISSUE TITLE
Possible bug in InitRHIFromExisting with high precision indices

### ISSUE THREAD

**Issue by muchcharles** [KoderzUnreal/RuntimeMeshComponent#184]
class FRuntimeMeshIndexBuffer : public FIndexBuffer
    [...]
    void InitRHIFromExisting(const FIndexBufferRHIRef& InIndexBufferRHI, int32 NumElements, bool bShouldUseHighPrecision)
    {

        [...]
        IndexSize = CalculateStride(bShouldUseHighPrecision);
        [...]
            IndexBufferRHI = CreateRHIBuffer<true>(CreateInfo, sizeof(uint16), 0, bIsDynamicBuffer);
    }

I think CreateRHIBuffer should be being called with IndexSize, not sizeof(uint16).  I haven't used this function so didn't actually run into a problem, just spotted it while searching for something else in the code.

**Comment by Koderz** [comment]
Hey @muchcharles 

I went ahead and changed it! in theory it shouldn't matter as that path is simply creating an empty buffer to use as a resource swap target so it's not actually creating the underlying GPU buffer so it shouldn't have caused an issue but either way better to go ahead and fix it!
